version: '3.7'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app